SET IDENTITY_INSERT [dbo].[Users] ON 
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (1, N'LimeAdmin', N'Green2022###!', N'Admin', NULL)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (3, N'admin', N'Green2022###!', N'Admin', NULL)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (5, N'betty@bettyjacobs.com', N'betty1', N'Rep', 2)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (7, N'delgallant@hotmail.com', N'gallant2', N'Rep', 4)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (8, N'd.delrio@telus.net_removed20210506', N'', N'Rep', NULL)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (9, N'pssales@on.aibn.com', N'pam4', N'Rep', 6)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (10, N'j_farese@sbcglobal.net', N'joanne5', N'Rep', 7)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (11, N'kathyfed@yahoo.com', N'kathy6', N'Rep', 8)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (12, N'Marjimem2@comcast.net', N'marji7', N'Rep', 9)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (14, N'Emily@thekleingrouponline.com', N'klien9', N'Rep', NULL)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (15, N'busybee@abitofhoney.com', N'honey10', N'Rep', 12)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (18, N'nrha', N'houseaccount5', N'Rep', 15)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (19, N'halleysinger@sbcglobal.net', N'halleysinger16', N'Rep', 16)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (22, N'harv0203@aol.com', N'harvey02', N'Rep', 19)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (23, N'hartmant001@hawaii.rr.com', N'hartm@n20', N'Rep', 20)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (24, N'josrags@aol.com', N'torr3s21', N'Rep', 21)
INSERT [dbo].[Users] ([ID], [LoginID], [Password], [UserType], [RepId]) VALUES (25, N'info@landrshowroom.com', N'l3rsh00', N'Rep', 22)
SET IDENTITY_INSERT [dbo].[Users] OFF
